spring.application.name=agile-agent
langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY:demo}
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.chat-model.temperature=0.0
jira.url=${JIRA_URL:demo}
jira.username=${JIRA_USERNAME:demo}
jira.token=${JIRA_API_KEY:demo}
jira.project-key=${JIRA_PROJECT_KEY:demo}
security.keys.public=classpath:keys/app.pub
security.keys.private=classpath:keys/app.key
spring.security.oauth2.resourceserver.jwt.issuer-uri=${APP_ISSUER:agile-agent}
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.datasource.url=jdbc:mariadb://localhost:3306/agiledatabase
spring.datasource.username=agileagent
spring.datasource.password=agileagent@631
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop